### ISSUE TITLE
About the performance on Lego, using Instant-NGP.

### ISSUE THREAD

**Issue by helcpp** [KAIR-BAIR/nerfacc#101]
It's a great job. It helps me a lot.
In the case of Instant-NGP, the Lego results had a slightly lower PSNR than in the paper, about 35.69. Which parameter should I adjust to improve my accuracy?
This question makes me very confused and I am looking forward to your reply.

Here is my output:

root@container-a2b311863c-63d7f839:/home/gzx/code/nerfacc# python examples/train_ngp_nerf.py --train_split train --scene lego
elapsed_time=1.67s | step=0 | loss=0.07278 | alive_ray_mask=256 | n_rendering_samples=66200 | num_rays=256 |
elapsed_time=130.57s | step=10000 | loss=0.00058 | alive_ray_mask=16749 | n_rendering_samples=267778 | num_rays=50257 |
elapsed_time=267.00s | step=20000 | loss=0.00037 | alive_ray_mask=16798 | n_rendering_samples=260996 | num_rays=51154 |
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [00:41<00:00,  4.81it/s]
evaluation: psnr_avg=35.549825792312625
training stops
root@container-a2b311863c-63d7f839:/home/gzx/code/nerfacc# python examples/train_ngp_nerf.py --train_split train --scene lego
elapsed_time=1.56s | step=0 | loss=0.07278 | alive_ray_mask=256 | n_rendering_samples=66200 | num_rays=256 |
elapsed_time=130.64s | step=10000 | loss=0.00059 | alive_ray_mask=17210 | n_rendering_samples=273457 | num_rays=51594 |
elapsed_time=266.61s | step=20000 | loss=0.00038 | alive_ray_mask=16845 | n_rendering_samples=260156 | num_rays=51493 |
elapsed_time=402.35s | step=30000 | loss=0.00031 | alive_ray_mask=17114 | n_rendering_samples=263116 | num_rays=52361 |
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [00:42<00:00,  4.72it/s]
evaluation: psnr_avg=35.69479295730591
training stops

**Comment by liruilong940607** [comment]
Hi, our webpage has up-to-date performance. Please checkout here: https://www.nerfacc.com/en/latest/examples/ngp.html

**Comment by helcpp** [comment]
I really appreciate your help.
