### ISSUE TITLE
distortion loss

### ISSUE THREAD

**Issue by cv-lab-x** [KAIR-BAIR/nerfacc#106]
hi, thanks for your great work! i found the the def distortion loss in loss codes, but they are not be used in any codes? did your test the distortion loss in the trainning pipeline? @brentyi @liruilong940607 
looking forward to your reply!

**Comment by liruilong940607** [comment]
Hi it is a preview feature that we haven't fully tested. We plan to test it in our next release.

The doc page contains all the stable functions:
https://www.nerfacc.com/en/latest/apis/utils.html

**Comment by kwea123** [comment]
There is already one: https://github.com/sunset1995/torch_efficient_distloss
which can be directly used with `nerfacc`. I already tried and it's working good
