### ISSUE TITLE
Possibility to use OccupancyGrid for generalizable NeRF

### ISSUE THREAD

**Issue by junzhezhang** [KAIR-BAIR/nerfacc#119]
Hi, 

Thanks for the amazing work!

I am quite curious if this framework can be used in a generalizable setting? If, let's say, we have prior knowledge of the occupancy of the N scenes in the train set and M scenes in the test set, in the form of 64x64x64 grids, do we have a way to maintain a new OccupancyGrid for each scene and manually store the prior occupancy into it?

Hope I made myself clear.

Thank you!
Junzhe

**Comment by liruilong940607** [comment]
Hi I'm working on a new version of `nerfacc` which will support for generalizable nerfs. Current version unfortunately does not work with generalizable nerfs because the OccupancyGrid does not support taking in prior knowledge.

**Comment by junzhezhang** [comment]
Hi Ruilong,

Great! Do you have a rough timeline for this?

Btw, if you need any sort of "customer requirement" for generalizable and generative case, I am willing to discuss with you:)

Junzhe

**Comment by liruilong940607** [comment]
Hi I'm supporting the proposal network way from Mip-NeRF 360, which would support accelerating generalizable nerfs. Still working on it

**Comment by ttsesm** [comment]
I see, thanks.

**Comment by liruilong940607** [comment]
With the [proposal network estimator](https://www.nerfacc.com/en/stable/methodology/sampling.html#proposal-network-estimator) supported in `nerfacc>=0.5.0` this should be doable. Basically just create a cheaper version of your network as the proposal network, and feed it with whatever input you feed to your main nerf, and train them jointly.

We don't have a specific example for generalizable nerfs but the example [here](examples/train_ngp_nerf_prop.py) should be easily applicable to generalizable nerfs.
