### ISSUE TITLE
Density threshold

### ISSUE THREAD

**Issue by MaximKuklin** [KAIR-BAIR/nerfacc#121]
Hello! Thank you for your implementation! Right now I'm working on converting output density to PNG slices like it's done in the instant-ngp repo - [link](https://github.com/NVlabs/instant-ngp/blob/master/src/testbed.cu#L326). These slices are used to generate a point cloud. 

In instant-ngp they have a threshold=2.5 as default, so the final equation for png slices looks like `slices=(density - 2.5) * 32 + 128.5` and then slices are clipped into the range from 0 to 255. So I'm curious about this 2.5 threshold and how to properly calculate it in your implementation. Do you have any tips on how to threshold density correctly?

**Comment by liruilong940607** [comment]
Hi you can still use `2.5` in `nerfacc`. I'm  not sure if there is a way to properly calculate this threshold as it relates to your network and ray marching step size. Generally `2 ~ 5` works fine.

**Comment by MaximKuklin** [comment]
Thank you!
