### ISSUE TITLE
Tiny error in if statement

### ISSUE THREAD

**Issue by nlml** [KAIR-BAIR/nerfacc#122]
https://github.com/KAIR-BAIR/nerfacc/blob/76c0f9817da4c9c8b5ccf827eb069ee2ce854b75/examples/train_ngp_nerf.py#L203

Should this not be:
`                    if (near_plane is not None) and (far_plane is not None):`?

**Comment by liruilong940607** [comment]
Hi this has been fixed in the master! See #97

**Comment by nlml** [comment]
Oops, didn't realise I wasn't on the master branch - thanks! :)
