### ISSUE TITLE
Why only update the grid in aabb?

### ISSUE THREAD

**Issue by kwea123** [KAIR-BAIR/nerfacc#126]
https://github.com/KAIR-BAIR/nerfacc/blob/0e1e7cb7c6f8e7e77073bc88f1333fddc7474c18/nerfacc/grid.py#L218-L222

Why don't you update the whole space?

**Comment by liruilong940607** [comment]
Hi this is because the contraction formulation in MipNeRF360 contracts inf into a sphere. So I'm only update things in the sphere not the cube. Note here masking the outer (2x) sphere which has radius 0.5 in a [0, 1] cube.
