### ISSUE TITLE
Pybind11 required version

### ISSUE THREAD

**Issue by lkskstlr** [KAIR-BAIR/nerfacc#127]
Hi nerfacc team,

thank you for open-sourcing this software, it is really useful!

I wanted to ask if the pybind requirement `pybind11>=2.10.0` is strict or if `pybind11==2.9.2` would also be sufficient (maybe not tested)? Are there specific features of `2.10` you are using?

Thanks a lot
Lukas

**Comment by liruilong940607** [comment]
I didn't test on various `pybind11` versions. It is very likely that a lower version would work as there is no special features being used. Personally I'm also not familiar with the change log of `pybind11`. Happy to take advices or PRs!!

**Comment by liruilong940607** [comment]
close at not activated any more
