### ISSUE TITLE
Calculate bounding box?

### ISSUE THREAD

**Issue by AIBluefisher** [KAIR-BAIR/nerfacc#133]
Hi, @liruilong940607 

I noticed nerfacc has a piece of code for calculating a rough bounding box:
```py
    if args.auto_aabb:
        camera_locs = torch.cat(
            [train_dataset.camtoworlds, test_dataset.camtoworlds]
        )[:, :3, -1]
        args.aabb = torch.cat(
            [camera_locs.min(dim=0).values, camera_locs.max(dim=0).values]
        ).tolist()
        print("Using auto aabb", args.aabb)
```
The bounding box calculated this way can potentially be too small for the desired area since some cameras observe outside. I wonder whether it is possible to calculate a bounding box from sparse point clouds (reconstructed by COLMAP), or is it necessary?

**Comment by liruilong940607** [comment]
If you have access to the point clouds surely it would be good to compute the bbox from that

**Comment by AIBluefisher** [comment]
I'm implementing this and plan to add it as a feature to nerfacc.
