### ISSUE TITLE
C++ and CUDA compile errors on Windows, VS 2019

### ISSUE THREAD

**Issue by ptc-lexvandersluijs** [KAIR-BAIR/nerfacc#144]
I'm running into this issue in two projects: using instant-ngp in NeRF-Studio and in instant-nsr-pl: [https://github.com/bennyguo/instant-nsr-pl](https://github.com/bennyguo/instant-nsr-pl)

Focusing on the latter:
I have updated requirements.txt to use nerfacc==0.3.2 instread of 0.2.2, but this doesn't solve it.

Installing the requirements works fine, but there are many compilation errors when I execute this command: `python launch.py --config configs/nerf-blender.yaml --gpu 0 --train dataset.scene=lego tag=example`

This is with the latest update of Visual Studio, and CUDA 11.6.

I've attached the full error log below, from a single run, for clarity.

Hope this can be solved, instant-nsr-pl looks like a very promising library!

[Windows VS2019 build error log.txt](https://github.com/KAIR-BAIR/nerfacc/files/10412458/Windows.VS2019.build.error.log.txt)

**Comment by ptc-lexvandersluijs** [comment]
Wait, now I see that version 0.3.2 is from 2 weeks ago, but there is a fix in this repo that mentions at least the size_t issue from 3 days ago, so my change in the requirements.txt wasn't useful (enough).

Maybe you could give me a pointer here: what is the best way to start using the module in this git-repository directly, instead of waiting until the module in the module-repository has been updated?

**Comment by liruilong940607** [comment]
Starting from this version we will have pre-built wheels provided so that you can directly install it:

https://github.com/KAIR-BAIR/nerfacc/releases/tag/v0.3.4
