### ISSUE TITLE
Error: No module named 'tinycudann'!

### ISSUE THREAD

**Issue by sunrainyg** [KAIR-BAIR/nerfacc#157]
After installing the torch (1.10.0) and cudatoolkit (10.2) and running the `pip install nerfadc`
when I run `python examples/train_ngp_nerf.py --train_split train --scene lego`
I will have the error: `Error: No module named 'tinycudann'! Please install tinycudann by: pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch`
And I try to install the tinycudann, but I will get another error of installation failure.

Also, I have tried another way of installation:
`pip install git+https://github.com/KAIR-BAIR/nerfacc.git` . I will get the error of CUDA build

Can you help me with the problem I met?

**Comment by liruilong940607** [comment]
The fact that you are not able to install both tiny-cuda-nn and our repo, makes me suspect that you might have incompatible torch v.s. cuda installed?

**Comment by sunrainyg** [comment]
I installed torch (1.10.0) and cudatoolkit (10.2) by running
`conda install pytorch==1.10.0 torchvision==0.11.0 torchaudio==0.10.0 cudatoolkit=10.2 -c pytorch`
cuda version is 10.2
So there should not exit incompatibility between torch and cuda installed?

**Comment by PJunGH** [comment]
@sunrainyg 
I encountered the same problem as you. I will appreciate it if you tell me how to solve it.
