### ISSUE TITLE
Support for LLFF dataset?

### ISSUE THREAD

**Issue by AIBluefisher** [KAIR-BAIR/nerfacc#160]
Hi, @tancik @liruilong940607 

I wonder if nerfacc can have a test on the LLFF dataset since I found very weird results when training InstantNGP with nerfacc's pipeline. There is a related [issue](https://github.com/KAIR-BAIR/nerfacc/issues/120).

**Comment by liruilong940607** [comment]
Unfortunately we didn't play with LLFF with NDC. But I do know someone treated LLFF as an `unbounded` scene and can train it with our unbounded script. 

If you are using NDC, I can imagine that those hyper-parameter such as `render_step_size`, `aabb`, `near`, `far` etc would need to be adjusted.

**Comment by AIBluefisher** [comment]
Thanks for your suggestion. Actually, I follow the dataset loading of [ngp_pl](https://github.com/kwea123/ngp_pl/blob/master/datasets/colmap.py) and tried without NDC. The results show InstantNGP overfits on the training set.
I also tried treating LLFF as an unbounded scene, the synthesized images are good on the validation set, but the depth images show nothing. (gt, rendered image, rendered depth)
![rgb_gt_0](https://user-images.githubusercontent.com/18096136/218235277-1585a71c-240b-44b2-8b7b-b7d22bfe960e.png)
![rgb_test_0](https://user-images.githubusercontent.com/18096136/218235248-4bb37744-fb30-474c-8d32-6903c608e8f1.png)
![depth_test_0](https://user-images.githubusercontent.com/18096136/218235255-9fe23091-11ce-4d04-b8ce-800b86224e76.png)

I did not find a suitable solution now.

**Comment by AIBluefisher** [comment]
It is the visualization issue for the depth map. Best viewed in the colorized **inverse** depth map.
![inv_depth_test_0](https://user-images.githubusercontent.com/18096136/218236568-3dc93078-4111-4003-ae52-d8f5b68b88d4.png)

**Comment by AIBluefisher** [comment]
Also tried to tune the bounding box size. The code is below:
```python
def visualize_poses(poses, size=0.1):
    # poses: [B, 4, 4]

    axes = trimesh.creation.axis(axis_length=4)
    # box = trimesh.primitives.Box(extents=(2, 2, 2)).as_outline()
    # box.colors = np.array([[128, 128, 128]] * len(box.entities))
    box = trimesh.creation.box(bounds=[[-5, -5, -5], [7, 5, 10]]) # the aabb corners that need to be tuned
    box.visual.face_colors = [0, 1., 0, 0.2]
    objects = [axes, box]

    for pose in poses:
        # a camera is visualized with 8 line segments.
        pos = pose[:3, 3]
        a = pos + size * pose[:3, 0] + size * pose[:3, 1] + size * pose[:3, 2]
        b = pos - size * pose[:3, 0] + size * pose[:3, 1] + size * pose[:3, 2]
        c = pos - size * pose[:3, 0] - size * pose[:3, 1] + size * pose[:3, 2]
        d = pos + size * pose[:3, 0] - size * pose[:3, 1] + size * pose[:3, 2]

        dir = (a + b + c + d) / 4 - pos
        dir = dir / (np.linalg.norm(dir) + 1e-8)
        o = pos + dir * 3

        segs = np.array([[pos, a], [pos, b], [pos, c], [pos, d], [a, b], [b, c], [c, d], [d, a], [pos, o]])
        segs = trimesh.load_path(segs)
        objects.append(segs)

    trimesh.Scene(objects).show()
```
Hope it can help someone else that has a similar issue as mine.

**Comment by aiyb1314** [comment]
How does nerfacc support LLFF datasets?
assert params is None, "Only support pinhole camera model."
AssertionError: Only support pinhole camera model.
