### ISSUE TITLE
Occupancy Grid visualization

### ISSUE THREAD

**Issue by yyashpatel** [KAIR-BAIR/nerfacc#162]
Hi,

How can I see/visualize the occupancy grid using **nerfacc.OccupancyGrid(roi_aabb, resolution=128, contraction_type=ContractionType.AABB**) ?

**Comment by yyashpatel** [comment]
okay I think I figured it out, Thanks.

**Comment by MobiusLqm** [comment]
@yyashpatel  Hi，Could you please share your method of visualizing the  occupancy grid? I'm curios about it.
