### ISSUE TITLE
How does nerfacc figure out t_min and t_max + other minor queries

### ISSUE THREAD

**Issue by NagabhushanSN95** [KAIR-BAIR/nerfacc#169]
Hi, I am trying to port my existing NeRF codebase to use nerfacc. I had a few queries.

1. In Readme, you mention that, we only need to define two functions: `sigma_fn` and `rgb_sigma_fn`. However, when I look at [train_nerf_mlp.py](https://github.com/KAIR-BAIR/nerfacc/blob/15330b4c51b32251195aa8c19e10b252563963d2/examples/train_mlp_nerf.py), I observe many new things. One of them is OccupancyGrid. I imagine you use this to not query unnecessary samples. So, without this, we wouldn't get the 1hr training time, right? Correct me if I'm wrong. Also, any idea what would be the training time without the occupancy grid?
2. While going through the `train_nerf_mlp.py` file, I noticed that you pass `None` values for `near_plane` and `far_plane` to the `ray_marching` function, but in the `sigma_fn`, the values passed to `t_starts` and `t_ends` are in the range `2--6`. How does this magic happen? How does it know the near and far values?
3. I want to train on custom datasets (which are like LLFF) with ndc enabled. I went through some of the issues that discuss ndc and LLFF. I had a couple of queries since those issues didn't exactly answer mine. 
3a. When calling ray_marching, if I pass the near and far values from my dataset to `near_plane` and `far_plane`, would it work fine?
3b. Since I have ndc enabled, can I pass the following values to aabb? `[-1.5, -1.5, 0, 1.5, 1.5, 1]`. Basically, I'm asking if I can set bounds in z dimension as `[0,1]`.

Thank you!

**Comment by liruilong940607** [comment]
1. Correct. Skipping with OccupancyGrid is where the major speed up comes from.
2. There is a bounding box being passed in to the ray_marching, in which a ray-aabb intersection is used to determinate the per-ray near far.
3a. It would of course work.
3b. Yeah it should work but I never test the rectangle aabb. Let me know if you find anything strange.

**Comment by NagabhushanSN95** [comment]
Thanks for the clarifications :)

**Comment by Ling27** [comment]
Hi, thanks for this great work. I am trying to speed up NSFF (https://github.com/zhengqili/Neural-Scene-Flow-Fields) using Nerfacc. However, I face several questions and I seek your guidance
1. NSFF has two MLPs: dynamic MLP and static MLP. I noticed that in train_mlp_dnerf.py, two MLPs are bound as one radiance field. In my implementation, I use two occupancy fields: one for dynamic MLP and one for static. May I know whether this implementation is suitable?
2. I have problems with ray_marching. Giving rays, scene=aabb, occupancy_grid_static, and sigma_fn as input to ray_marching function, the outputs: ray_indices, t_starts and t_ends are all empty. Is the problem from the aabb values? I use the same value [-1.5, -1.5, -1.5, 1.5, 1.5, 1.5] here.
3.
