### ISSUE TITLE
Inconsistency in the use of dirs and view_dirs when obtaining 3D points

### ISSUE THREAD

**Issue by NagabhushanSN95** [KAIR-BAIR/nerfacc#170]
In the original nerf implementation, `directions` and `views` were two different variables. Essentially, `views` were unit vectors along `directions`. `views` were used as input to the second NeRF MLP, whereas `directions` were used to compute the location of 3D points as `pts_loc = origins + t_vals * directions`. But [`rays_marching()` takes only the normalized `views` as input](https://github.com/KAIR-BAIR/nerfacc/blob/15330b4c51b32251195aa8c19e10b252563963d2/examples/utils.py#L88), which means the same is passed to `sigma_fn` and thus 3D point locations are computed as `pts_loc = origins + t_vals * views`. 

Wouldn't this cause a problem? Or did I understand something incorrectly?

**Comment by WHUTzmy** [comment]
The t_vals in nerf are the distances in the z-axis direction, and t_vals * directions are translated into the actual distance between the two points. And nerfacc uses t_start and t_end to calculate the distance, which is the actual distance between two points.

**Comment by NagabhushanSN95** [comment]
Thank you for the clarification.
