### ISSUE TITLE
Are there no coarse and fine NeRF in train_mlp_nerf.py?

### ISSUE THREAD

**Issue by NagabhushanSN95** [KAIR-BAIR/nerfacc#171]
Hi,

I noticed that in [train_mlp_nerf.py](https://github.com/KAIR-BAIR/nerfacc/blob/15330b4c51b32251195aa8c19e10b252563963d2/examples/train_mlp_nerf.py) file, a NeRF MLP is queried only once with stratified sampling. Do you not use hierarchical sampling with coarse and fine MLPs?

**Comment by WHUTzmy** [comment]
Yes, they don't use coarse to fine network，because they use another strategy to optimize the sampling process , they use an occupied_grid to skip the empty region, which is mentioned  in instant-ngp.

**Comment by NagabhushanSN95** [comment]
Okay, I'll check that. Thanks!
