### ISSUE TITLE
Have you compare with torch-ngp

### ISSUE THREAD

**Issue by yerfor** [KAIR-BAIR/nerfacc#196]
Hi， great work to accelerate NeRF！ Have you compare the performance with another popular repo, torch-ngp?

**Comment by liruilong940607** [comment]
Hi they reported [34.15 psnr on Lego](https://github.com/ashawkey/torch-ngp#performance-reference) with 30k iterations on train set. In comparison, we got [35.67 psnr in 20k steps] (https://www.nerfacc.com/en/stable/examples/static/ngp.html)

**Comment by yerfor** [comment]
That's cool, thanks for reply!
