### ISSUE TITLE
proposal net estimator - low reconstruction quality

### ISSUE THREAD

**Issue by yyashpatel** [KAIR-BAIR/nerfacc#199]
I was testing with the proposal network estimator to train the nerf . The reconstruction quality is not good.

What could be the reason ? When I have trained the same data using nerfstudio, it performs well . 

Was just curious whether there is any implementation difference .? 

Thanks

**Comment by liruilong940607** [comment]
There is not any major difference that we know of. One thing is that we got rid of the annealing bc we didn’t find it useful, and it is not quite compatible with our implementation.

Actually how were you using it? Using the script in this repo or porting it into another repo?

**Comment by yyashpatel** [comment]
I am using the python APIs in my code . 
Not using the script directly given in the nerfacc repo

**Comment by liruilong940607** [comment]
Any more information that you can provide? Like how did you actually using it in your code. For your reference, there is another example where we plug in the prop net into TiNeuVox’s code and that works fine:

https://github.com/liruilong940607/tineuvox/blob/a4feb27444d86c0ced5952930f7a41d5345d2b59/lib/tineuvox.py#L563

**Comment by yyashpatel** [comment]
Thanks for the reference, based on it and also the code provided in the examples folder in this nerfacc repo, I have a similar implementation.


In one dataset it works well, in some other dataset it produces a bad quality. I have attached the bad results below - 

![000002](https://user-images.githubusercontent.com/87276851/232345488-e3c99395-31bd-4b78-b502-d0cedf98c6e9.png)
![000004](https://user-images.githubusercontent.com/87276851/232345493-bbad4d20-246c-4180-9a0c-a9b96d66bb9d.png)
![000009](https://user-images.githubusercontent.com/87276851/232345495-eac44598-dd38-4e5c-bf1b-73cc79dc4541.png)

are there any hyperparamters needed to be tuned ?

**Comment by liruilong940607** [comment]
Are those two images both with nerfacc’s proposal? The first one seems to be much worst than the second one.

One info that I can share is, from my experiments the proposal way seems to be quite sensitive to the network you set as the proposal network. Your first image reminds me some of previous failure experiments, where I resolved by tuning the hyper parameters of the proposal network.

Are you using tinycudann as the underlying network or your own thing?

**Comment by liruilong940607** [comment]
Also when you say you were training the same data with nerfstudio, does that mean you were using the nerfacto model? And when you use nerfacc in your own repo, do you still use the nerfacto model?

**Comment by yyashpatel** [comment]
1) Yes the outputs are from the proposal network of nerfacc. And I am using tinycudann as the underlying network.
     By hyper-parameter tuning of the proposal network you mean proposal samples ?

2) when training with nerfstudio yes I use the nerfacto model. And when I use nerfacc in my repo, I use the network provided by you in the nerfacc repo. The only change I see in the network is appearance embeddings which is present in nerfacto.

**Comment by yyashpatel** [comment]
Hi, changing parameters of proposal network and also number of samples gives considerable results . 

I am closing the issue for now , thanks again !
