### ISSUE TITLE
Measuring mesh 

### ISSUE THREAD

**Issue by LHXhh** [KAIR-BAIR/nerfacc#210]
Thank you very much for your wonderful work, and now I have a question for you.  I have UAV image data of real pose. The mesh range derived after training with nerf has been normalized. What should I do to restore the range of real scene, that is, the result obtained from traditional 3D reconstruction, so that the exported mesh is measurable?  Thank you very much ！

**Comment by liruilong940607** [comment]
For nerf 360 data we normalize the scene like this:

https://github.com/KAIR-BAIR/nerfacc/blob/0be61b2aabdc73bf9d019ff1066404cb29c6ed04/examples/datasets/nerf_360_v2.py#L244-L249

I'm not sure what's your data processing pipeline but if it is like this one, then you just need to `/= sscale` for the mesh you extracted.

**Comment by LHXhh** [comment]
Thank you very much.
