### ISSUE TITLE
questions about paper equation

### ISSUE THREAD

**Issue by LuckyOne09** [KAIR-BAIR/nerfacc#218]
Hi, thank you for your excellent work, but I have some questions regarding the derivation of an equation in the paper.
![image](https://github.com/KAIR-BAIR/nerfacc/assets/38714962/35088555-6cd5-42bf-b361-bf12c523aea2)
Thank you for your time and assistance. I appreciate your willingness to help me better understand your work.

**Comment by liruilong940607** [comment]
Hi yeah we omit some details in the paper, which we provide here:

<img width="843" alt="Screen Shot 2023-05-13 at 9 10 20 AM" src="https://github.com/KAIR-BAIR/nerfacc/assets/10151885/72e7119c-7d6d-48f4-b4c2-a59745275538">

**Comment by LuckyOne09** [comment]
Wow, thank you for your so quick and detailed explanation. I can understand now and I am amazed that you could come up with such a clever deduction.
