### ISSUE TITLE
No module named 'lpips'

### ISSUE THREAD

**Issue by liuxin2322** [KAIR-BAIR/nerfacc#225]
when i run dynamic scene example, triggle bug as below:

Traceback (most recent call last):
  File "/content/nerfacc/examples/train_mlp_tnerf.py", line 16, in <module>
    from lpips import LPIPS
ModuleNotFoundError: No module named 'lpips'

**Comment by liruilong940607** [comment]
Hi you need to install dependence here before running the examples:

https://github.com/KAIR-BAIR/nerfacc/blob/master/examples/requirements.txt

**Comment by liuxin2322** [comment]
> Hi you need to install dependence here before running the examples:
> 
> https://github.com/KAIR-BAIR/nerfacc/blob/master/examples/requirements.txt

Thank you very much, it worked! 
Have you considered providing a Colab example, such as training a static or dynamic
 scene? It would be very intuitive and convenient for newcomers.
：)

**Comment by liruilong940607** [comment]
That would be great but we actually have another repo [nerfstudio](https://github.com/nerfstudio-project/nerfstudio), which is very friendly for starters with many functionality (even viewer).

**Comment by liuxin2322** [comment]
> That would be great but we actually have another repo [nerfstudio](https://github.com/nerfstudio-project/nerfstudio), which is very friendly for starters with many functionality (even viewer).

ok.  I encountered another  issue  when attempting to train DNERF example . I found that there is no dataset available. Where can I download a dataset?
```
atasets/dnerf_synthetic.py", line 28, in _load_renderings
    with open(
FileNotFoundError: [Errno 2] No such file or directory: '/content/nerfacc/examples/datasets/../../data/dnerf/lego/transforms_train.json
```

**Comment by liruilong940607** [comment]
You can find D-NeRF dataset here: https://github.com/albertpumarola/D-NeRF#download-dataset
