### ISSUE TITLE
OccGridEstimator sampling() Is there a gradient?

### ISSUE THREAD

**Issue by zsy950116** [KAIR-BAIR/nerfacc#226]
Hi, Thanks for your work! 
      OccGridEstimator sampling() Can backpropagation be carried out？
      I use the 0.3 ray_marching function, but when the input is graded, the output gradient disappears.
      Do you have a solution？Thank you very much.

**Comment by liruilong940607** [comment]
The `sampling()` (the old `ray_marching()`) function is simply not differentiable w.r.t the input. 

What's the case that you would need this function to be differentiable?

**Comment by zsy950116** [comment]
Yeah, but I found I could skip this step. But thank you for your answer
