### ISSUE TITLE
Would 3D AABB affect the training?

### ISSUE THREAD

**Issue by FlyCole** [KAIR-BAIR/nerfacc#234]
Hello,

I'm now trying to squeeze the 3D aabb bounding box used by NGPradianceField() and OccupancyGrid() generation, in order to eliminate the floaters. (I'm not so sure if that makes sense, but intuitively it does.) However, I found that if the bounding box is too tight for the object (for example double the volume of the tightest aabb), the training is just wrong, leading to either grayscale 2D rendering or darker 2D rendering, like the images below. But after I enlarge the 3D aabb to almost include the whole scene, everything goes well.
May I ask if the 3D AABB really affects the training or if there should be some bugs within my code? Thank you!
![rgb_0000](https://github.com/KAIR-BAIR/nerfacc/assets/36623811/d655a2bb-e103-4dd9-9246-8a4cf7720232)
![obj1_rgb_test_63](https://github.com/KAIR-BAIR/nerfacc/assets/36623811/7b5597fe-2eab-42de-9f7c-4303c437435e)

**Comment by liruilong940607** [comment]
The AABB definitely affects training but I would say what you get is reasonable.

I guess one way to debug this is to first make sure the AABB you are setting is a reasonable AABB that does contain the object you want to focus one. And then you can gradually adjust the AABB, starting with the one that can make everything work and see when it starts to make things fall part and investigate why.
