### ISSUE TITLE
ImportError: cannot import name 'csrc' from 'nerfacc'

### ISSUE THREAD

**Issue by Binyr** [KAIR-BAIR/nerfacc#259]
when using nerfacc=0.3.5 and 0.4.0, it raises "ImportError: cannot import name 'csrc' from 'nerfacc'"; 
when using nerfacc>=0.5.0, it raises "module 'nerfacc' has no attribute 'OccupancyGrid".

How to solve it, thank you~!

**Comment by fengyuli-dev** [comment]
Hi, have you found a solution?

**Comment by lxycopper** [comment]
same problem, do you have solved it?
