### ISSUE TITLE
NAN

### ISSUE THREAD

**Issue by Yannnnnnnnnnnn** [KAIR-BAIR/nerfacc#55]
Thanks for your sharing.

I tried to run the examples of mlp, but the network output was NAN. 
Can you give me some suggestions?

![image](https://user-images.githubusercontent.com/17909171/194477898-f997f571-02c4-4e1f-8002-6d13d2fd5238.png)

**Comment by liruilong940607** [comment]
Oh nice catch! It is a bug introduced in the recent update. Just fixed in #56. And bump the version to v0.1.6.
