### ISSUE TITLE
TrainVal split usage

### ISSUE THREAD

**Issue by lukasHoel** [KAIR-BAIR/nerfacc#64]
Hi,

thanks for the awesome project!

according to https://github.com/kwea123/ngp_pl/pull/1 and https://github.com/NVlabs/instant-ngp/discussions/745 only the train-split was used in Instant-NGP's results.

Do you also have the numbers for only using the train split? :)

**Comment by liruilong940607** [comment]
Oh thanks for pointing it out Lukas! I didn't notice this clarification so thought it was using trainval split.

So I did a quick test on Chair, using train test gives me 35.17db, comparing to 36.13db on trainval set. For reference NGP paper reports 35.00db for this scene. (5mins)

Still, the NGP paper uses random bkgd argumentation I think (at least that is by default enabled in their code base). And I believe that would give some boost to the performance.

We will do a full test soon.

**Comment by liruilong940607** [comment]
Hi we did a full test in #68. Turns out under the fair comparison setting, both the performance and runtime are nearly the same. Sorry for the confusing!
