### ISSUE TITLE
the error when "pip install nerfacc"

### ISSUE THREAD

**Issue by gld17** [KAIR-BAIR/nerfacc#71]
ERROR: No matching distribution found for nerfacc

**Comment by liruilong940607** [comment]
What's your pip version?

Could you try `pip install --upgrade pip` then `pip install nerfacc`?

**Comment by liruilong940607** [comment]
Also `nerfacc` require `python>=3.8`.  So I would check my python version as well.

**Comment by liruilong940607** [comment]
Closr for now. Feel free to reopen it if there is still obstacles
