### ISSUE TITLE
Setting up CUDA (This may take a few minutes the first time)Killed

### ISSUE THREAD

**Issue by LHXhh** [KAIR-BAIR/nerfacc#81]
Could you please help me?
(nerfacc)root@container-804a11b7ac-5f6a35c5:~/autodl-tmp# /root/miniconda3/envs/nerf/bin/python /root/autodl-tmp/nerfacc/examples/train_mlp_nerf.py
(  ●   ) NerfAcc: Setting up CUDA (This may take a few minutes the first time)Killed

torch ==1.12.1+cu102
RTX 2080 Ti

**Comment by liruilong940607** [comment]
Don't kill the job when it is setting up CUDA

**Comment by LHXhh** [comment]
Thank you very much, I have solved it.

**Comment by yyashpatel** [comment]
Hi , I have the same issue . I had to install nerfacc again . 

Now it gets stuck at -
NerfAcc: Setting up cuda (This May take few minutes)

My laptop freezes during this step.

**Comment by doramasma** [comment]
@LHXhh Hello! I'm facing the same problem, could you tell me what u did to solve it ? 

Thanks in advance  :)

**Comment by liruilong940607** [comment]
Hi did you try with #70 ?

**Comment by LHXhh** [comment]
I have tried with [https://github.com/KAIR-BAIR/nerfacc/issues/70](url), but it was still wrong, so I reset the environment, and it works normally.

My environment
nvcc -V            cuda_11.3
gcc --version        9.4.0
g++ --version        9.4.0
Pytorch         1.12.1+cu113
NVIDIA RTX A5000


Command
conda create --name nerfacc python=3.9
conda activate nerfacc

pip install nerfacc

pip uninstall torch
pip install torch-1.12.1+cu113-cp39-cp39-linux_x86_64.whl
pip install torchvision-0.13.1+cu113-cp39-cp39-linux_x86_64.whl

**Comment by doramasma** [comment]
Hello! 

I have tried what u proposed but still killed the process. I suspect it may be because I am running out of resources since I have been able to run it on a more powerful machine.
