### ISSUE TITLE
ImportError:cannot import name 'SceneManager' from 'scene_manager'

### ISSUE THREAD

**Issue by LHXhh** [KAIR-BAIR/nerfacc#86]
It works on lego dataset, but ween I try the llff dataset, There is an ImportError, could you please help me. 
And I have seen the package in /root/miniconda3/envs/nerfacc/lib/python3.9/site-packages/scene_manager, There is nothing package such as SceneManager.
Thank you very much.

(nerfacc) root@container-0f5011ad3c-f66f17d1:~/autodl-tmp/nerfacc# python examples/train_mlp_nerf.py --scene garden --unbounded
Using unbounded rendering
Traceback (most recent call last):
  File "/root/autodl-tmp/nerfacc/examples/train_mlp_nerf.py", line 113, in <module>
    from datasets.nerf_360_v2 import SubjectLoader
  File "/root/autodl-tmp/nerfacc/examples/datasets/nerf_360_v2.py", line 22, in <module>
    from scene_manager import SceneManager
ImportError: cannot import name 'SceneManager' from 'scene_manager' (/root/miniconda3/envs/nerfacc/lib/python3.9/site-packages/scene_manager/__init__.py)

scene-manager      0.1.0

**Comment by liruilong940607** [comment]
please see https://github.com/KAIR-BAIR/nerfacc/issues/69#issue-1407041875

**Comment by LHXhh** [comment]
Thank you very much！

**Comment by LHXhh** [comment]
One more question, I want to train the llff dataset by  python ./examples/train_mlp_nerf.py --train_split train --scene garden --unbounded --cone_angle=0.004，but there is something wrong with it.
If I want to train the llff dataset, what should I do? Thank you very much.

 (nerfacc) root@container-0f5011ad3c-f66f17d1:~/autodl-tmp/nerfacc# python ./examples/train_mlp_nerf.py --train_split train --scene garden --unbounded
Using unbounded rendering
Traceback (most recent call last):
  File "/root/autodl-tmp/nerfacc/./examples/train_mlp_nerf.py", line 128, in <module>
    train_dataset = SubjectLoader(
  File "/root/autodl-tmp/nerfacc/examples/datasets/nerf_360_v2.py", line 186, in __init__
    self.images, self.camtoworlds, self.K = _load_colmap(
  File "/root/autodl-tmp/nerfacc/examples/datasets/nerf_360_v2.py", line 101, in _load_colmap
    assert params is None, "Only support pinhole camera model."
AssertionError: Only support pinhole camera model.

**Comment by liruilong940607** [comment]
Hi I'm not quite familiar with llff dataset so I'm afraid I can help you with that.

**Comment by LHXhh** [comment]
Never mind, Thank you very much.
