### ISSUE TITLE
How to visualize?

### ISSUE THREAD

**Issue by Learningm** [KAIR-BAIR/nerfacc#87]
I trained the model and get psnr value successfully.

How to visualize it ? It seems no checkpoint saved during the whole process.

**Comment by liruilong940607** [comment]
Uncomment this line will save the image.

https://github.com/KAIR-BAIR/nerfacc/blob/107d7466ef3fcfadd64e8b57ad3c1aafd4874fe0/examples/train_mlp_nerf.py#L254

**Comment by Learningm** [comment]
Is it convenient to turn this vanilla nerf into plenoctree structure? 
Plenoctree is a repo based on JAX, it seems that this needs a lot of effort to achieve the conversion.

**Comment by liruilong940607** [comment]
For that you would need to do modifications in the Plenoctrees repo: https://github.com/sxyu/plenoctree

It is not too much efforts as the conversion logic is fairly straightforward. But it is out of the scope of this repo

**Comment by liruilong940607** [comment]
If you just want to visualize a nerf with PlenOctree, I would recommend you to checkout this repo:

https://github.com/sxyu/nerfvis

It will do the conversion and visualization for you in one line.

**Comment by Learningm** [comment]
wow, pretty cool ! Thanks and I will try it.
