### ISSUE TITLE
NerfAcc: No CUDA toolkit found. NerfAcc will be disabled.

### ISSUE THREAD

**Issue by ial-amanna** [KAIR-BAIR/nerfacc#89]
I have a local cuda-toolkit 11.6.2 and Pytorch with cuda 11.6 along with tiny cudnn. 
However when I run the examples, I come across this error. 

NerfAcc: No CUDA toolkit found. NerfAcc will be disabled.

File "/home/annamalai/nerfacc/cuda/__init__.py", line 13, in call_cuda
    return getattr(_C, name)(*args, **kwargs)

AttributeError: 'NoneType' object has no attribute 'ContractionType'

Although I also get a warning that FullyFused MLP is not supported for the selected architecture.

I'm not sure why this happens.

**Comment by liruilong940607** [comment]
This indicates there is no `nvcc` command found. Please check your cuda environment is properly setup so that if you run `nvcc` in your terminal it is a valid command

**Comment by ial-amanna** [comment]
Thanks for the message. Yes, I set it up properly, now it works!

**Comment by 1406428260** [comment]
hello  I have same question, but my nvcc seting is correct,how to solve it, thanks
![image](https://user-images.githubusercontent.com/41857725/221391181-cfcaa291-d4f0-41a8-8eed-e8450bec8712.png)

**Comment by WenhongZhang** [comment]
> hello I have same question, but my nvcc seting is correct,how to solve it, thanks ![image](https://user-images.githubusercontent.com/41857725/221391181-cfcaa291-d4f0-41a8-8eed-e8450bec8712.png)

Same problem in a docker container. Did you solve it?

**Comment by yuchenlichuck** [comment]
sAME HERE I CAN RUN IN TERMINAL BUT I CAN'T RUN IT IN PYCHARM

**Comment by Lingyun0109** [comment]
> sAME HERE I CAN RUN IN TERMINAL BUT I CAN'T RUN IT IN PYCHARM
请问你找到原因了吗？

**Comment by BaiBF** [comment]
> sAME HERE I CAN RUN IN TERMINAL BUT I CAN'T RUN IT IN PYCHARM

can you fix the bug?
