### ISSUE TITLE
how to visualize the train step

### ISSUE THREAD

**Issue by liwenssss** [KAIR-BAIR/nerfacc#90]
hello , I want to visualize the predicted image when training to show the efficiency of ngp. Is there any relevant settings in the code ?

**Comment by liruilong940607** [comment]
You can uncomment here:

https://github.com/KAIR-BAIR/nerfacc/blob/107d7466ef3fcfadd64e8b57ad3c1aafd4874fe0/examples/train_ngp_nerf.py#L298

**Comment by liwenssss** [comment]
thanks for your reply. Is it possible to use nerfacc to speed up human-nerf (such as [animatable_nerf](https://github.com/zju3dv/animatable_nerf)) training? I tried to embed nerfacc in it, but found that some of the Settings were hard to align..

**Comment by liruilong940607** [comment]
You can refer to the d-nerf example. human-nerfs are very much like that. You just need to have a more customized warping field conditioned on human pose instead of timestamps. 

Checkout the explanation of the d-nerf usage here: https://www.nerfacc.com/en/latest/examples/dnerf.html

**Comment by liwenssss** [comment]
I tried but got empty ray_indices when eval. It's weird. Do you know what might have caused it. Or do you have plan to give an example on zju dataset?
