### ISSUE TITLE
initial values for OccupancyGrid

### ISSUE THREAD

**Issue by vahidEttehadi** [KAIR-BAIR/nerfacc#93]
I have a quick question out of curiosity regarding the initial values for OccupancyGrid. 

Do the initial values from some prior geometries for OccupancyGrid accelerate the process? did you try it? Thanks in advance!

**Comment by liruilong940607** [comment]
You may actually want to the initialize the radiance field network instead of the occupancy grid, as the occupancy grid is designed to synchronize with the radiance field network.

**Comment by vahidEttehadi** [comment]
OK. Thanks!

**Comment by Abc11c** [comment]
Hi,

I want to force render some parts present in the occupancy grid, I'm looking for something like [here](https://github.com/KAIR-BAIR/nerfacc/blob/561c6c5ae2a44f902f9f8bba3e53e7df78fdbe92/tests/test_grid.py#L55). 

But I'm working on v3.5 (1x occ_grid) any ideas how to proceed ? 

need something during eval, similar to `occ_eval_fn` to update the states of the grid points in trainging

Thanks!
