### ISSUE TITLE
Meaning of accumulated depth

### ISSUE THREAD

**Issue by marlinilram** [KAIR-BAIR/nerfacc#95]
Hi, thanks for this great project! I have a question about depth returned from `rendering()` , it is computed by
```python
depths = accumulate_along_rays(
        weights,
        ray_indices,
        values=(t_starts + t_ends) / 2.0,
        n_rays=n_rays,
    )
```
Usually the t_starts and t_ends is the distance along ray, so the returned depth mesuares the point-to-point distance. If I require a point-to-plane depth (to compute a depth loss from some sensor measurements), I need an extra coefficient `dot(ray_d, camera_forward)` right?

**Comment by liruilong940607** [comment]
Yeah you are correct.

**Comment by marlinilram** [comment]
tks!
