### ISSUE TITLE
bug in train_ngp_nerf.py

### ISSUE THREAD

**Issue by CZ-Wu** [KAIR-BAIR/nerfacc#97]
It seems a bug here:
> https://github.com/KAIR-BAIR/nerfacc/blob/e7bd2074c583c287b9d0f575398b68a2517cb546/examples/train_ngp_nerf.py#L203

should be `if (near_plane is not None) and (far_plane is not None):`?

**Comment by CCamouflage-Hvv** [comment]
I have the same question. Hope a senior guy come to explain. Thanks!

**Comment by liruilong940607** [comment]
Good catch. Yeah it is a typo just fixed. It shouldn't cause any issue by far as near far planes are either both None, or both valid.
