### ISSUE TITLE
How can I train my own c2w transform data?

### ISSUE THREAD

**Issue by CCamouflage-Hvv** [KAIR-BAIR/nerfacc#98]
Hi!
Thanks for your great job!
I am trying to use your code to train a nerf model with my own dataset.
What I want to know the form of the transform matrixes that you used. My data's form is c2w, but I got a wrong result. Are you using w2c?
Thanks again!

**Comment by liruilong940607** [comment]
The examples are using c2w. But you might need be careful about whether your camera is in opencv or opengl format.

Though this is not related to the nerfacc library itself. As nerfacc handles the `rays` directly. You have to make sure you create the rays in a correct way, using your cameras.
