### ISSUE TITLE
CUDA out of memery

### ISSUE THREAD

**Issue by LHXhh** [KAIR-BAIR/nerfacc#99]
I test unbounded dataset garden in the train_mlp_nerf, which works well during training process, but there is something wrong during testing. Is that normal? Thank you very much.
![飞书20221104-143539](https://user-images.githubusercontent.com/102360620/199907469-d6f6afde-7237-480e-ba54-6e047e6f0823.png)

**Comment by liruilong940607** [comment]
Simply because the GPU you are using doesn't not have enough GPU memory to support this task. Testing would require extra memory.

**Comment by liruilong940607** [comment]
You can use smaller `target_sample_batch_size` to save memory for training, or `chunk_size` to save memory for inference. Or sample less points via reducing `render_n_samples`

**Comment by LHXhh** [comment]
I will have a try, Thank you.
